### ISSUE TITLE
Download through file name

### ISSUE THREAD

**Issue by jrcamelo** [DiscordTime/gdrive-manager#15]
Getting a file ID is not very user friendly, and we should be able to download using the file name instead.

We should be able to get the file ID with the file name using the [list method](https://developers.google.com/drive/api/v3/reference/files/list), which returns a list of files with a certain query.

I believe the query should search for the file name, get only the file ID and maybe the file size, order by modified time desc, and limit to 1 item per page. That way we can download the latest file if something is found. Or maybe show information for that file to make sure the user is not downloading the wrong file.

Perhaps the command could be `$ gdrive download name some_file.gz`, or even take the current file ID download place if necessary, making it an alternative download option instead.

**Comment by psteiger** [comment]
`$ gdrive download name some_file.gz`: I believe `some_file.gz` is not needed. `$ gdrive download name` suffices, and the file name written to the filesystem will be the same as the name in Google Drive.

**Comment by carlosolimpio** [comment]
How would you differ files with the same name already stored into drive?

**Comment by jrcamelo** [comment]
As @psteiger explained, `$ gdrive download name some_file.gz` should have been `$ gdrive download --name some_file.gz`

@carlosolimpio, you can order by some factors, like the modified time, and I believe the normal use-case for that would be the latest file with that name.
