### ISSUE TITLE
Ensure PEP 8 (code style) adherence.

### ISSUE THREAD

**Issue by psteiger** [DiscordTime/gdrive-manager#9]
PEP 8 is no bible, but should be majorly followed for consistency. https://www.python.org/dev/peps/pep-0008/

**Comment by psteiger** [comment]
@viniciusalbuquerque I propose we make this a "permanent issue". PEP 8 violations will eventually come by again and we could reuse this issue to keep track.

**Comment by viniciusalbuquerque** [comment]
Okay, I'm fine with that.

**Comment by psteiger** [comment]
This is now automatically tracked by `pylint` through CI (issue #21) so we don't need to track PEP-0008 adherence manually anymore. Closing.
